// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
